# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a727e9f919795bc2af89306028e1a86ae33bbd25d0713c7d5b2e1f09cec00ef3a204b21848c0f8a1afaeaf9d388d1897375de14c92b0f090b63012806ced44ab
  admin_name: Preston
  admin_email: preston.copeland@namely.com
  admin_password: Admin123!
  manager_1_name: Gerry
  manager_1_email: gerry.mandell@namely.com
  manager_1_password: KoalaAttack!
  basic_user_1_name: Tonye
  basic_user_1_email: tonye.taylorharry@namely.com
  basic_user_1_password: KoalaAttack!
  basic_user_2_name: Carol
  basic_user_2_email: carol.mirakove@namely.com
  basic_user_2_password: KoalaAttack!

test:
  secret_key_base: e24da6ea6a45faa8cf0a9e5d617ab8ced23d80fc1870014d9e9c86cc8fa10a92ca661019883d3fb199b8058a6a8f7c63c2148d3239663586362c1c36e61347ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

